function dYdt = PC2_sys(t,Y,m,b,l,h,k,m_b,m_c,g,S)
%PC2_sys
%    dYdt = PC2_sys(T,Y,M,B,L,H,K,M_B,M_C,G,S)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    19-Apr-2024 20:04:47

t2 = Y(2);
t3 = Y(3);
t4 = Y(4);
t5 = m.^2;
t6 = cos(t3);
t7 = t5+1.0;
t8 = sqrt(t7);
t9 = 1.0./t8;
dYdt = [t2;(t9.*(-k.*t8.*sqrt((b.^2.*t7)./t5)+S.*k.*t8+g.*m.*m_b+g.*m.*m_c-k.*t8.*Y(1)+l.*m_b.*t4.*t6.*t8))./(m_b+m_c);t4;-(t9.*(g.*sin(t3)-g.*m.*t6+t2.*t6.*t8))./l];
end
